FROM ros:noetic

RUN mkdir ./catkin_ws
COPY . ./catkin_ws/
WORKDIR ./catkin_ws

RUN apt-get update \
	&& apt-get install --no-install-recommends -y \
		ros-noetic-moveit-commander \
		ros-noetic-panda-moveit-config \
	&& bash -c "source devel/setup.bash && rosdep install --from-paths src --ignore-src -r -y" \
	&& rm -rf /var/lib/apt/lists*

RUN bash -c "source devel/setup.bash && catkin_make"

CMD ["/bin/bash", "-c", "source ./devel/setup.bash && roslaunch --wait spd_controller controller.launch"]
